version: '3.5'

services:

  php:
    image: likesistemas/php-dev:${PHP_VERSION}
    entrypoint: bash
    command: composer test:ci
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - GITHUB_OWNER=$GITHUB_OWNER
      - GITHUB_REPO=$GITHUB_REPO
      - GITHUB_PR_NUMBER=$GITHUB_PR_NUMBER
      - TEST_LANG=$TEST_LANG
      - TEST_TITLE=$TEST_TITLE
      - TEST_FOOTER=$TEST_FOOTER
    volumes:
      - ./:/var/www/
    stdin_open: true
    tty: true