version: '3.7'
networks:
  github:
    name: github
    driver: bridge

services:

  nginx:
    image: likesistemas/nginx:latest
    environment:
      - HOST_PHP=php
      - PORTA_PHP=9000
      - INDEX_FILE=index.php
    volumes:
      - ./public/:/var/www/public/
    ports:
      - 8081:80
    networks:
      - github
    links:
      - php
    depends_on:
      - php

  php:
    image: likesistemas/php-dev:${PHP_VERSION:-56}
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - GITHUB_OWNER=$GITHUB_OWNER
      - GITHUB_REPO=$GITHUB_REPO
      - GITHUB_PR_NUMBER=$GITHUB_PR_NUMBER
      - TEST_LANG=$TEST_LANG
      - TEST_TITLE=$TEST_TITLE
      - TEST_FOOTER=$TEST_FOOTER
      - IMGBB_TOKEN=$IMGBB_TOKEN
    volumes:
      - ./:/var/www/
    networks:
      - github
  
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444
    networks:
      - github
    links:
      - php
      - nginx
    depends_on:
      - php
      - nginx