name: PHP 7.4

on:

  push:
    branches:
      - master

  pull_request:

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare code
        run: |
          touch .env
          echo "GITHUB_OWNER=likesistemas" >> .env
          echo "GITHUB_REPO=codeception-github-reporter" >> .env
          echo "GITHUB_PR_NUMBER=${{github.event.number}}" >> .env
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env
          echo "IMGBB_TOKEN=${{ secrets.IMGBB_TOKEN }}" >> .env
          echo "PHP_VERSION=74" >> .env

      - name: Run tests
        run: |
          docker-compose up -d
          echo $(docker run -t --network github jwilder/dockerize -wait http://nginx/ -timeout 60s)
          docker-compose ps
          docker-compose logs php
          docker-compose exec -T php composer test:ci
          docker-compose down